/*
 *  Java
 *
 */
package com.logient;

/**
 * Generated by the build-firmware-singleapp-skeleton.<br>
 * Please keep it in sync with the property 'application.main.class' defined in module.ivy
 */
public class Main {
	
	/**
	 * Simple main.
	 *
	 * @param args
	 *            command line arguments.
	 */
	public static void main(String[] args) {
		System.out.println("Hello World!"); //$NON-NLS-1$
	}
}
