/*
 *  Java
 *
 */
package com.logient;

import com.logient.material.MaterialTheme;
import com.logient.widget.navigationdrawer.DrawerContainer;
import com.logient.widget.navigationdrawer.DrawerItem;
import com.logient.widget.scrollablelist.Scroll;
import com.logient.widget.scrollablelist.ScrollableList;

import ej.microui.MicroUI;
import ej.mwt.Desktop;
import ej.mwt.Widget;
import ej.widget.basic.ImageWidget;
import ej.widget.basic.Label;
import ej.widget.container.LayoutOrientation;

/**
 * Generated by the build-firmware-singleapp-skeleton.<br>
 * Please keep it in sync with the property 'application.main.class' defined in module.ivy
 */
public class Main {

	/**
	 * Simple main.
	 *
	 * @param args
	 *            command line arguments.
	 */
	public static void main(String[] args) {
		MicroUI.start();

		Desktop desktop = new Desktop();

		desktop.setStylesheet(App.getTheme());

		DrawerContainer root = new DrawerContainer(App.getTheme(), createDrawerItems());

		desktop.setWidget(root);

		desktop.requestShow();
	}

	private static DrawerItem[] createDrawerItems() {
		MaterialTheme theme = App.getTheme();
		DrawerItem[] drawerItems = { new DrawerItem(theme, "Label #1", new Label("This is a first label")),
				new DrawerItem(theme, "Label #2", new Label("This is a second label")),
				new DrawerItem(theme, "Label #3", new Label("This is a third label")),
				new DrawerItem(theme, "Label #4", new Label("This is fourth label")),
				new DrawerItem(theme, "Label #5", new Label("This is a fifth label")),
				new DrawerItem(theme, "Label #6", new Label("This is a sixth label")),
				new DrawerItem(theme, "Label #7", new Label("This is a seventh label")),
				new DrawerItem(theme, "Label #8", new Label("This is a eighth label")),
				new DrawerItem(theme, "Label #9", new Label("This is a ninth label")),
				new DrawerItem(theme, "Image", new ImageWidget("/images/microej_background.png")),
				new DrawerItem(theme, "Typos", createTypoList()) };
		return drawerItems;
	}

	private static Widget createTypoList() {

		ScrollableList list = new ScrollableList(LayoutOrientation.VERTICAL);
		list.addChild(createLabel("h1", Styles.h1));
		list.addChild(createLabel("h2", Styles.h2));
		list.addChild(createLabel("h3", Styles.h3));
		list.addChild(createLabel("h4", Styles.h4));
		list.addChild(createLabel("h5", Styles.h5));
		list.addChild(createLabel("body1", Styles.body1));
		list.addChild(createLabel("body2", Styles.body2));
		list.addChild(createLabel("subtitle", Styles.subtitle));
		list.addChild(createLabel("h1", Styles.h1));
		list.addChild(createLabel("h1", Styles.h1));
		list.addChild(createLabel("h1", Styles.h1));
		list.addChild(createLabel("h1", Styles.h1));

		Scroll scroll = new Scroll(LayoutOrientation.VERTICAL);
		scroll.setChild(list);
		scroll.setEnabled(false);
		return scroll;
	}

	private static Label createLabel(String value) {
		return createLabel(value, Styles.body1);
	}

	private static Label createLabel(String value, int classSelector) {
		Label label = new Label(value);
		label.addClassSelector(classSelector);
		return label;
	}
}
